const assert = require('node:assert/strict');
const fs = require('node:fs');

const html = fs.readFileSync('options.html', 'utf8');
const script = fs.readFileSync('src/pages/settings/options.js', 'utf8');
const background = fs.readFileSync('background.js', 'utf8');

assert.doesNotMatch(html, /Connectez Jira-Quick-Search/);
assert.doesNotMatch(html, /Ce que vous pouvez faire/);
assert.match(html, /id="connection-heading"/);
assert.match(html, /Connexion Jira/);
assert.match(html, /chrome:\/\/extensions\/shortcuts/);
assert.match(html, /barre d’adresse/);
assert.match(html, /appuyez sur Espace ou Tab/);
assert.match(html, /id="connectBtn"/);
assert.match(html, /id="retryBtn"/);
assert.match(html, /type="password"/);
assert.match(html, /Diagnostics/);
assert.match(html, /id="diagnosticBtn"/);
assert.match(html, /Supprimer toutes les données locales/);
assert.match(html, /Aucune donnée n’est envoyée à un serveur tiers/);
assert.match(html, /Aide et feedback/);
assert.match(html, /Signaler un problème/);
assert.match(html, /Proposer une fonctionnalité/);
assert.match(html, /id="feedbackForm"/);
assert.match(html, /id="feedbackMessage"[^>]*aria-live="polite"/);
assert.match(html, /Aucune donnée n’est envoyée automatiquement/);
assert.match(html, /id="accordion-collapse-body-1"/);
assert.match(html, /data-accordion-target="#accordion-collapse-body-1"/);
assert.match(html, /Aide et raccourcis/);
assert.doesNotMatch(html, /Revoir l’introduction/);
assert.match(script, /accordionButton\.addEventListener\('click'/);
assert.match(script, /setAttribute\('aria-expanded'/);
assert.match(script, /chrome\.storage\.sync\.set\(\{ jiraUrl: url, jiraEmail: email, jiraToken: token \}\)/);
assert.match(script, /window\.location\.href = 'search\.html'/);
assert.match(script, /Connexion réussie/);
assert.match(script, /Impossible de se connecter/);
assert.match(script, /retryBtn/);
assert.match(script, /window\.confirm\(/);
assert.match(script, /clearExtensionData\(chrome\.storage\)/);
assert.match(script, /window\.location\.href = 'options\.html'/);
assert.match(script, /prepareFeedback/);
assert.match(script, /buildGithubIssueUrl/);
assert.match(script, /chrome\.tabs\.create\(\{ url \}\)/);
assert.doesNotMatch(script, /chrome\.storage\.local\.set\(.*feedback/i);
assert.match(background, /chrome\.runtime\.getURL\('onboarding\.html'\)/);
assert.match(background, /chrome\.tabs\.create\(\{\s*url: chrome\.runtime\.getURL\('search\.html'\)/s);
assert.match(background, /config\.jiraUrl && config\.jiraEmail && config\.jiraToken/);

console.log('onboarding: 13 tests passed');
